#!/usr/bin/env bash
# Undo node
npm uninstall -g yarn typescript-language-server typescript
sudo apt purge nodejs npm
rm /usr/local/lib/node_modules/n/bin/n
rm /usr/local/bin/n
rm /usr/local/bin/node

# Undo zsh
uninstall_oh_my_zsh
chsh /bin/bash
sudo apt purge zsh

# Undo Slack
sudo apt purge slack-desktop

# Undo Core Install
sudo apt purge curl htop stow tmux buildessential fzf lsof i3 gimp yarn python3-pip xclip slack nvidia-settings pavucontrol lua tldr
