- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    user: "{{ ansible_user_id }}"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_public_key: "./.ssh/id_rsa.pub"
    dest_public_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    source_intelephense_key: "./auth_codes/intelephense_backup_code"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tmux.yml
    - include: tasks/git.yml
    - include: tasks/composer.yml
    - include: tasks/slack-setup.yml
    - include: tasks/desktop.yml

