- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become_user: root
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "pipx"]
  tags:
    - install
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become_user: root
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - core

- name: Install System Packages 3 (the rest)
  become_user: root
  apt:
    name: ["curl", "htop", "i3", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol"]
  tags:
    - install
    - core

- name: Install all other usefull packages
  become_user: root
  apt:
    name: ["tmux","fzf","xclip","tldr", "direnv", "python3", "python", "ctags","php-cli", "ripgrep", "fd-find", "stow", "feh", "xss-lock","xdotool", "compton", "lxappearance", "gimp"]
  tags:
    - install
    - core

- name: Install rofi dependencies
  become_user: root
  apt:
    name: ["flex", "bison", "libxcb-cursor-dev", "libsdl-pango-dev", "libstartup-notification0-dev", "libgdk-pixbuf2.0-dev"]
  tags:
    - install
    - core
    - rofi

- name: Install i3-gaps repository
  become_user: root
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
  tags:
    - install
    - core

- name: Install PHP 8.1 repository
  become_user: root
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
  tags:
    - install
    - core
    - php

- name: Install PHP 8.1
  become_user: root
  apt:
    name: ["php8.1", "php8.1-mbstring", "php8.1-mysql"]
    update_cache: yes
  tags:
    - install
    - core
    - php

- name: Install i3-gaps
  become_user: root
  apt:
    name: "i3-gaps"
    update_cache: yes
  tags:
    - install
    - core

- name: Install python3 provider
  shell: python3 -m pip install --user --upgrade pynvim
  tags:
    - install
    - core
