- name: update-alternatives for kitty default shell
  become_user: root
  shell: "update-alternatives --install `which x-terminal-emulator` x-terminal-emulator `which kitty` 50"
  ignore_errors: yes
  tags:
    - install
    - desktop
    - kitty

- name: ensure git directory
  file:
    path: "{{ lookup('env', 'HOME') }}/git"
    state: directory

- name: ensure work directory
  file:
    path: "{{ lookup('env', 'HOME') }}/work"
    state: directory

- name: check is polybar installed
  shell: command -v polybar
  register: polybar_exists
  ignore_errors: yes
  tags:
    - desktop
    - polybar
    - install

- name: install polybar
  tags:
    - desktop
    - install
    - polybar
  when: polybar_exists is failed
  block:
  - name: install polybar dependencies
    become_user: root
    apt:
      name:
        - cmake
        - cmake-data
        - libcairo2-dev
        - libjsoncpp-dev
        - libxcb-composite0-dev
        - libxcb-ewmh-dev
        - libxcb-randr0-dev
        - libxcb1-dev
        - python3-sphinx
        - python3-xcbgen
        - xcb-proto
        - libasound2-dev
        - libcurl4-openssl-dev
        - libmpdclient-dev
        - python3-packaging
        - libuv1-dev
        - libxcb-util0-dev
        - libxcb-image0-dev
        - libxcb-icccm4-dev
        - libiw-dev
        - libpulse-dev
  - name: clone polybar
    ansible.builtin.git:
      repo: 'https://github.com/jaagr/polybar.git'
      dest: "{{ lookup('env', 'HOME') }}/git/polybar"
      update: no

- name: install i3lock-color
  tags:
    - desktop
    - install
    - i3lock
  block:
  - name: install i3lock-color dependencies
    become_user: root
    apt:
      name:
        - gcc
        - make
        - libpam0g-dev
        - libfontconfig1-dev
        - libev-dev
        - libx11-xcb-dev
        - libxcb-xkb-dev
        - libxcb-xinerama0-dev
        - libxcb-util-dev
        - libxcb-xrm-dev
        - libxcb-xtest0-dev
        - libxkbcommon-dev
        - libxkbcommon-x11-dev
        - libjpeg-dev
        - scrot
        - imagemagick
  - name: clone i3lock-color
    ansible.builtin.git:
      repo: 'https://github.com/Raymo111/i3lock-color.git'
      dest: "{{ lookup('env', 'HOME') }}/git/i3-lock-color"
      update: no

- name: Create themes dir if it does not exist
  file:
    path: "{{ lookup('env', 'HOME') }}/.themes"
    state: directory
    mode: '0755'
  tags:
    - install
    - desktop

- name: Create icons dir if it does not exist
  file:
    path: "{{ lookup('env', 'HOME') }}/.icons"
    state: directory
    mode: '0755'
  tags:
    - install
    - desktop

- name: Extract serenade in themes
  ansible.builtin.unarchive:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/themes/serenade.zip"
    dest: "{{ lookup('env', 'HOME') }}/.themes"
  tags:
    - install
    - desktop

- name: Extract Flatery in icons
  ansible.builtin.unarchive:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/themes/Flatery.zip"
    dest: "{{ lookup('env', 'HOME') }}/.icons"
  tags:
    - install
    - desktop

- name: Remove Animation GTK
  shell: gsettings set org.gnome.desktop.interface enable-animations false
  tags:
    - install
    - desktop

- name: change GTK theme to Serenade
  shell: gsettings set org.gnome.desktop.interface gtk-theme serenade
  tags:
    - install
    - desktop

- name: change Windows manager theme to Serenade
  shell: gsettings set org.gnome.desktop.wm.preferences theme serenade
  tags:
    - install
    - desktop

- name: change GTK icons to Flatery
  shell: gsettings set org.gnome.desktop.interface icon-theme Flatery
  tags:
    - install
    - desktop

- name: Install real program dvorak layout
  shell: sudo cp ~/.config/xkb/symbols/real-prog-dvorak /usr/share/X11/xkb/symbols/real-prog-dvorak
  tags:
    - install
    - desktop
    - layout
