- name: add git global email
  shell: git config --global user.email "16608904+Taloud@users.noreply.github.com"
  tags:
    - install
    - git
- name: add git global user
  shell: git config --global user.name "Taloud"
  tags:
    - install
    - git
- name: add git global editor
  shell: git config --global core.editor "nvim"
  tags:
    - install
    - git
- name: make ansible git ssh origin
  shell: "cd {{ lookup('env', 'HOME') }}/ansible && git remote set-url origin git@github.com:Taloud/ansible.git"
  tags:
    - install
    - git
- name: make dotfile git ssh origin
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && git remote set-url origin git@github.com:Taloud/dotfiles.git"
  tags:
    - install
    - git
