- name: Install System Packages required for nvim
  become_user: root
  apt:
    name:
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - libncurses5-dev
      - g++
      - python-dev
      - python3-dev
      - python3-pip
      - ruby
      - ruby-dev
  tags:
    - install
    - neovim

- name: Neovim Installation
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make"
  tags:
    - install
    - neovim

- name: Install neovim
  become_user: root
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Check if vim-plug is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
  register: vim_plug_path
  tags:
    - install
    - dotfiles
    - neovim

- name: Install Vim-Plug
  when: vim_plug_path.stat.islnk is not defined
  shell: curl -fLo {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - dotfiles
    - neovim

- name: Install vim Plugins
  ignore_errors: yes
  shell: nvim -u ~/.config/nvim/plugins.vim +PlugClean +qall
  tags:
    - install
    - dotfiles
    - neovim
