- name: Install System Packages required for nvim
  become_user: root
  apt:
    name:
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - libncurses5-dev
      - g++
      - python-dev
      - python3-dev
      - python3-pip
      - ruby
      - ruby-dev
  tags:
    - install
    - neovim

- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Neovim Installation
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim

- name: Install neovim
  become_user: root
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Check if Packer directory exist
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer"
  register: packer_path
  tags:
    - install
    - dotfiles
    - neovim

- name: Install Packer
  when: packer_path.stat.isdir is not defined
  shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  tags:
    - install
    - dotfiles
    - neovim

