- name: Install packages
  become_user: root
  apt:
    name: ["tmux","fzf","xclip","tldr","kitty"]
  tags:
    - install
    - productivity

- name: update-alternatives for kitty default shell
  become_user: root
  shell: "update-alternatives --install `which x-terminal-emulator` x-terminal-emulator `which kitty` 50"
  ignore_errors: yes
  tags:
    - install
    - kitty

- name: Download Composer
  shell: cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php
  tags:
    - install
    - productivity
    - php
- name: Install Composer
  become_user: root
  shell: "php {{ lookup('env', 'HOME') }}/composer-setup.php --install-dir=/usr/local/bin --filename=composer && rm {{ lookup('env', 'HOME') }}/composer-setup.php"
  tags:
    - install
    - productivity
    - php
