- name: Install packages
  become_user: root
  apt:
    name: ["tmux","fzf","xclip","tldr"]
  tags:
    - install
    - productivity

- name: Check if kitty exists
  shell: command -v kitty
  register: kitty_exists
  ignore_errors: yes
  tags:
    - install
    - kitty

- name: install kitty
  when: kitty_exists is failed
  shell: |
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest={{ lookup('env', 'HOME') }}/.local/stow
    cd {{ lookup('env', 'HOME') }}/.local/stow
    stow -v kitty.app
    sudo update-alternatives --install `which x-terminal-emulator` x-terminal-emulator `which kitty` 50
  tags:
    - install
    - kitty

- name: Download Composer
  shell: cd ~ && curl -sS https://getcomposer.org/installer -o composer-setup.php
  tags:
    - install
    - productivity
    - php
- name: Install Composer
  become_user: root
  shell: "php {{ lookup('env', 'HOME') }}/composer-setup.php --install-dir=/usr/local/bin --filename=composer && rm {{ lookup('env', 'HOME') }}/composer-setup.php"
  tags:
    - install
    - productivity
    - php
