- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  become_user: root
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh public key
  become_user: root
  copy:
    src: "{{ source_public_key }}"
    dest: "{{ dest_public_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
